algoritmo "Exe020403"
   // 2 - fazer um algoritmo com suas informações pessoais
   var
     Nome,CPF,RG: caracter
     Idade: inteiro


   inicio
     escreva("Informe o NOme: ")
     leia(Nome)
     escreva("Informe a idade: ")
     leia(Idade)
     escreva("Informe o CPF: ")
     leia(CPF)
     escreva("Informe o RG: ")
     leia(RG)
     escreval("O nome: ",Nome," A idade: ",Idade)
     escreval("O CPF: ",CPF, " A Identidade(RG): ",RG)



fimalgoritmo
